### ISSUE TITLE
Number is not displaying!

### ISSUE THREAD

**Issue by dishankEbizz** [Ali-Rezaei/PadLayout#2]
Hello, Hope you are doing good.

When I am clicking on number of dialer the number is not displaying in display section. Can you please guide me for this?

Thanks in advance.

**Comment by alirezaeiii** [comment]
Thank you for your question. This sample is just showing you custom padLayout and is not supposed to show you more info. In this sample : https://github.com/alirezaeiii/Rebtel-Contacts-Clone it is showing you the numbers as well.

**Comment by dishankEbizz** [comment]
Thank you for quick response. If I want to change font color of number and alphabet then can I do it without implementing whole module?

**Comment by alirezaeiii** [comment]
No, at the moment this has not been implemented, so you need to make a change in the module.

**Comment by dishankEbizz** [comment]
Okay. Thanks

**Comment by alirezaeiii** [comment]
Hi again, in the padLayout there is a Style file that you can override in order to change the color : DialpadKeyNumberStyle and DialpadKeyLettersStyle. For instance check the style file of the sample link, I posted you above.

**Comment by dishankEbizz** [comment]
Okay. Thanks

**Comment by dishankEbizz** [comment]
It working fine now. Thanks for your quick help.
